'use client';

import { AdData, DashboardStats, CompetitorInsight } from '@/types';
import { Download, FileText, Share2, BarChart3, Award, TrendingUp, Clock, Target, Users } from 'lucide-react';
import { format } from 'date-fns';

interface Props {
    ads: AdData[];
    stats: DashboardStats;
    competitorInsights: CompetitorInsight[];
}

export default function ReportsView({ ads, stats, competitorInsights }: Props) {
    const topAds = ads.filter(a => a.isTopPerforming).sort((a, b) => b.adDuration - a.adDuration);
    const now = new Date();

    const generatePDFReport = () => {
        // Create printable report
        const reportContent = `
META ADS COMPETITOR INTELLIGENCE REPORT
Generated: ${format(now, 'MMMM dd, yyyy HH:mm')}
${'='.repeat(60)}

EXECUTIVE SUMMARY
-----------------
Total Ads Tracked: ${stats.totalAds}
Active Ads: ${stats.activeAds}
Unique Competitors: ${stats.uniqueCompetitors}
Average Ad Duration: ${stats.avgAdDuration} days
Top Performing Ads (30+ days): ${stats.topPerformingAds}

COMPETITOR BREAKDOWN
--------------------
${competitorInsights.map(c => `
${c.pageName}
  Total Ads: ${c.totalAds}
  Active: ${c.activeAds}
  Top Performing: ${c.topPerformingAds}
  Avg Duration: ${c.averageDuration} days
  Primary CTA: ${c.mostCommonCTA}
`).join('')}

TOP PERFORMING ADS (30+ days)
------------------------------
${topAds.slice(0, 10).map(ad => `
${ad.pageName} - ${ad.adDuration} days
CTA: ${ad.ctaText}
URL: ${ad.urlLink}
Ad Copy: ${ad.bodyText.slice(0, 200)}...
Analysis: ${ad.improvementScope.slice(0, 300)}...
`).join('\n')}

---
Report generated by Meta Ads Intelligence Dashboard
    `.trim();

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `meta-ads-report-${format(now, 'yyyy-MM-dd')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const exportJSON = () => {
        const data = {
            generatedAt: now.toISOString(),
            summary: stats,
            competitors: competitorInsights,
            ads: ads.map(({ id, pageName, bodyText, ctaText, urlLink, startedDate, endDate, adDuration, status, improvementScope }) => ({
                id, pageName, bodyText, ctaText, urlLink, startedDate, endDate, adDuration, status, improvementScope
            })),
        };
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `meta-ads-data-${format(now, 'yyyy-MM-dd')}.json`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6 animate-fade-in">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-xl font-bold text-white">Reports & Export</h1>
                    <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
                        Generate competitive intelligence reports for your team
                    </p>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={generatePDFReport}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium btn-primary text-white"
                    >
                        <Download size={15} />
                        Export Report
                    </button>
                    <button
                        onClick={exportJSON}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium btn-ghost"
                        style={{ color: 'var(--text-secondary)' }}
                    >
                        <FileText size={15} />
                        Export JSON
                    </button>
                </div>
            </div>

            {/* Report Summary Card */}
            <div
                className="p-6 rounded-xl"
                style={{
                    background: 'linear-gradient(135deg, rgba(99,102,241,0.15) 0%, rgba(124,58,237,0.1) 50%, rgba(236,72,153,0.05) 100%)',
                    border: '1px solid rgba(99,102,241,0.25)',
                }}
            >
                <div className="flex items-start justify-between">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <BarChart3 size={18} className="text-indigo-400" />
                            <span className="font-bold text-white">Competiter Intelligence Summary</span>
                        </div>
                        <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                            Generated on {format(now, 'MMMM dd, yyyy')} • Based on {stats.totalAds} ads from {stats.uniqueCompetitors} competitors
                        </p>
                    </div>
                    <button
                        onClick={() => {
                            const text = `Meta Ads Intel Report: ${stats.totalAds} ads tracked, ${stats.uniqueCompetitors} competitors, ${stats.topPerformingAds} top performers. Generated ${format(now, 'MMM dd yyyy')}`;
                            navigator.clipboard.writeText(text);
                        }}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm btn-ghost"
                        style={{ color: 'var(--text-secondary)' }}
                    >
                        <Share2 size={14} />
                        Share
                    </button>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mt-5">
                    {[
                        { label: 'Total Ads', value: stats.totalAds, icon: <Target size={14} />, color: '#6366f1' },
                        { label: 'Active', value: stats.activeAds, icon: <TrendingUp size={14} />, color: '#10b981' },
                        { label: 'Competitors', value: stats.uniqueCompetitors, icon: <Users size={14} />, color: '#f59e0b' },
                        { label: 'Avg Duration', value: `${stats.avgAdDuration}d`, icon: <Clock size={14} />, color: '#ec4899' },
                        { label: 'Top Performing', value: stats.topPerformingAds, icon: <Award size={14} />, color: '#06b6d4' },
                    ].map((item, i) => (
                        <div key={i} className="text-center">
                            <div className="flex justify-center mb-1" style={{ color: item.color }}>{item.icon}</div>
                            <div className="text-2xl font-bold text-white">{item.value}</div>
                            <div className="text-xs" style={{ color: 'var(--text-muted)' }}>{item.label}</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Competitor Reports */}
            <div>
                <h2 className="text-sm font-bold text-white mb-3">Competitor-wise Analysis Cards</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {competitorInsights.map((insight, i) => (
                        <div
                            key={i}
                            className="p-5 rounded-xl"
                            style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
                        >
                            {/* Header */}
                            <div className="flex items-start justify-between mb-4">
                                <div className="flex items-center gap-3">
                                    <div
                                        className="w-10 h-10 rounded-full flex items-center justify-center text-base font-bold text-white"
                                        style={{ background: `hsl(${insight.pageName.charCodeAt(0) * 15 % 360}, 60%, 45%)` }}
                                    >
                                        {insight.pageName.charAt(0)}
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-white">{insight.pageName}</h3>
                                        <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                                            {insight.totalAds} ads • {insight.activeAds} active
                                        </p>
                                    </div>
                                </div>
                                {insight.topPerformingAds > 0 && (
                                    <div className="flex items-center gap-1 badge-top px-2 py-1 rounded-full text-xs font-medium">
                                        <Award size={10} />
                                        {insight.topPerformingAds} top
                                    </div>
                                )}
                            </div>

                            {/* Metrics */}
                            <div className="grid grid-cols-3 gap-3 mb-4">
                                {[
                                    { label: 'Avg Duration', value: `${insight.averageDuration}d` },
                                    { label: 'Active Ads', value: insight.activeAds },
                                    { label: 'Primary CTA', value: insight.mostCommonCTA },
                                ].map((m, j) => (
                                    <div
                                        key={j}
                                        className="p-2 rounded-lg text-center"
                                        style={{ background: 'var(--bg-secondary)' }}
                                    >
                                        <div className="text-sm font-bold text-white truncate" title={String(m.value)}>{m.value}</div>
                                        <div className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>{m.label}</div>
                                    </div>
                                ))}
                            </div>

                            {/* CTA Breakdown */}
                            <div>
                                <p className="text-xs font-medium mb-2" style={{ color: 'var(--text-muted)' }}>CTA Distribution</p>
                                <div className="space-y-1.5">
                                    {Object.entries(insight.ctaDistribution).map(([cta, count], k) => {
                                        const total = insight.totalAds;
                                        const pct = Math.round((count / total) * 100);
                                        return (
                                            <div key={k} className="flex items-center gap-2">
                                                <span className="text-xs truncate flex-1" style={{ color: 'var(--text-secondary)' }}>{cta}</span>
                                                <div className="w-20 h-1.5 rounded-full overflow-hidden" style={{ background: 'var(--bg-primary)' }}>
                                                    <div
                                                        className="h-full rounded-full"
                                                        style={{
                                                            width: `${pct}%`,
                                                            background: `hsl(${insight.pageName.charCodeAt(0) * 15 % 360}, 60%, 55%)`,
                                                        }}
                                                    />
                                                </div>
                                                <span className="text-xs w-8 text-right font-medium" style={{ color: 'var(--text-muted)' }}>{pct}%</span>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Key Insights */}
            <div
                className="p-5 rounded-xl"
                style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
            >
                <h2 className="text-sm font-bold text-white mb-4">Key Intelligence Findings</h2>
                <div className="space-y-3">
                    {[
                        {
                            emoji: '🏆',
                            title: 'Longest Running Ad',
                            desc: topAds[0]
                                ? `${topAds[0].pageName} has the longest running ad at ${topAds[0].adDuration} days — likely very profitable`
                                : 'No top performing ads identified yet',
                        },
                        {
                            emoji: '🎯',
                            title: 'Most Active Competitor',
                            desc: competitorInsights[0]
                                ? `${competitorInsights[0].pageName} has the most ads (${competitorInsights[0].totalAds}) — very active advertiser`
                                : 'No data available',
                        },
                        {
                            emoji: '📣',
                            title: 'Most Common CTA',
                            desc: (() => {
                                const ctaMap: Record<string, number> = {};
                                ads.forEach(a => { ctaMap[a.ctaText || 'N/A'] = (ctaMap[a.ctaText || 'N/A'] || 0) + 1; });
                                const top = Object.entries(ctaMap).sort(([, a], [, b]) => b - a)[0];
                                return top ? `"${top[0]}" used ${top[1]} times — dominant conversion strategy` : 'No CTA data';
                            })(),
                        },
                        {
                            emoji: '⚡',
                            title: 'Average Campaign Length',
                            desc: `Competitors run ads for an average of ${stats.avgAdDuration} days. Ads running 30+ days are flagged as top performers.`,
                        },
                    ].map((finding, i) => (
                        <div
                            key={i}
                            className="flex items-start gap-3 p-3 rounded-xl"
                            style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
                        >
                            <span className="text-xl flex-shrink-0">{finding.emoji}</span>
                            <div>
                                <p className="text-sm font-semibold text-white">{finding.title}</p>
                                <p className="text-xs mt-0.5" style={{ color: 'var(--text-secondary)' }}>{finding.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
